import type { ApiEntry } from "@free-api-list/catalog";

export const FIXTURE_APIS: ApiEntry[] = [
  {
    id: "dog-api",
    name: "Dog API",
    description: "An API for dog breeds, groups, and facts. Useful when you need canine data.",
    category: "animals",
    difficulty: "beginner",
    baseUrl: "https://dogapi.dog/api/v2",
    documentationUrl: "https://dogapi.dog/docs/api-v2",
    auth: { required: false, type: "none" },
    endpoints: [{ path: "/breeds", method: "GET", description: "List breeds" }],
    tags: ["dogs", "breeds"],
    cors: "yes",
    https: true,
    pricing: "free",
    addedAt: "2023-06-01",
  },
  {
    id: "cataas",
    name: "Cat as a Service",
    description: "A REST API that returns random cat images and GIFs for cat-loving applications.",
    category: "animals",
    difficulty: "beginner",
    baseUrl: "https://cataas.com",
    documentationUrl: "https://cataas.com/doc.html",
    auth: { required: false, type: "none" },
    endpoints: [{ path: "/cat", method: "GET", description: "Random cat" }],
    tags: ["cats", "images"],
    cors: "yes",
    https: true,
    pricing: "free",
    addedAt: "2023-06-01",
  },
  {
    id: "art-institute",
    name: "Art Institute",
    description: "Open metadata for artworks in the Art Institute of Chicago collection.",
    category: "art-design",
    difficulty: "intermediate",
    baseUrl: "https://api.artic.edu/api/v1/artworks",
    documentationUrl: "https://api.artic.edu/docs/",
    auth: { required: false, type: "none" },
    endpoints: [{ path: "/", method: "GET", description: "List artworks" }],
    tags: ["art", "museum"],
    cors: "yes",
    https: true,
    pricing: "free",
    addedAt: "2023-06-01",
  },
  {
    id: "secret-api",
    name: "Secret API",
    description: "An advanced API that requires an API key for any kind of access whatsoever.",
    category: "authentication",
    difficulty: "advanced",
    baseUrl: "https://secret.example.com",
    documentationUrl: "https://secret.example.com/docs",
    auth: { required: true, type: "api_key" },
    endpoints: [{ path: "/secrets", method: "GET", description: "List secrets" }],
    tags: ["security", "secrets"],
    cors: "unknown",
    https: true,
    pricing: "freemium",
    addedAt: "2024-01-15",
  },
];
